[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Shinyoung Lee <shinyounglee.315@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.112.0"
uvicorn = "^0.30.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
